<?php

/**
 * @file
 * Custom functions and hooks for Etype Services
 * None Required for Fernandina
 *
 */

/**
 * Implements hook_menu().
 */
function etype_menu() {

    $items = array();

    $items['etype-classified-cleanup'] = array(
        'title' => t('Cleanup Classified Ads'),
        'page callback' => 'etype_classified_cleanup',
        'type' => MENU_CALLBACK,
        'access arguments' => array('access administration pages')
    );

    return $items;

}


function etype_classified_cleanup() {

    $res = db_query('SELECT n.nid FROM node n LEFT JOIN node_revision nr ON nr.nid = n.nid WHERE nr.vid IS NULL');
    var_dump($res);
}