<?php

/**
 * @file
 * Custom functions and hooks for Etype Services
 *
 */

/**
 * Implements hook_menu().
 */
function etype_login_menu() {

  $items['custom-login-page'] = array(
    'title' => 'Custom Login Page',
    'description' => 'eType Services Custom Login Page.',
    'access arguments' => array('access content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'etype_login_form'
    ),
    'menu_name' => 'user-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function etype_login_form($form, &$form_state) {

  $messages = drupal_get_messages();
  print_r($messages);

  $form["username"] = array(
    '#title' => t("User Name"),
    '#type' => 'textfield',
    '#required' => TRUE
  );

  $form["password"] = array(
    '#title' => t("Password"),
    '#type' => 'textfield',
    '#required' => TRUE
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Log In')
  );

  $form['help'] = array(
    '#type' => 'item',
    '#title' => '',
    '#markup' => '
<div class="login-help">
    <p><a href="/forgot-password">Forgot your password?</a></p>
</div>
    '
  );

  $form['#submit'][] = 'etype_login_form_submit';
  return $form;

}

function etype_login_form_submit($form, &$form_state) {
  $username = $form_state['values']['username'];
  $param = array('UserName' => $username);
  $client = new soapclient('https://etypeservices.com/service_GetPublicationIDByUserName.asmx?WSDL');
  $response = $client->GetPublicationID($param);
  print_r($response);
  if ($response->GetPublicationIDResult == '-9') {
    drupal_set_message("Invalid User Name or Password.", 'error');
  }
}

/**
 * @return string
 */
function _etype_login_fake() {

  $page = array('title' => 'Login');

  $destination = $_GET['destination'];
  $username = $_POST['name'];
  $Password = $_POST['password'];
  $_SESSION['uname'] = $_POST['name'];
  $_SESSION['upass'] = $_POST['password'];
  $param12 = array('UserName' => "$username");
  $client12 = new soapclient('https://etypeservices.com/service_GetPublicationIDByUserName.asmx?WSDL');
  $response12 = $client12->GetPublicationID($param12);


  if ($response12->GetPublicationIDResult == -9) {
    $msg = "Invalid User Name or Password. ";
  } else {
    if ($response12->GetPublicationIDResult == 3191) {
      $param = array('UserName' => "$username", 'Password' => "$Password");
      $client = new soapclient('https://etypeservices.com/Service_SubscriberLogin.asmx?WSDL');

      $response = $client->ValidateSubscriber($param);

      $param1 = array('UserName' => "$username");
      $client1 = new soapclient('https://etypeservices.com/Get_EmailbyUserName.asmx?WSDL');

      $response1 = $client1->GetSubscriberEmail($param1);


      $query = "select name, uid from users where name='" . $username . "'";
      $qu = db_query($query);

      $userexit = "";
      $useruid = "";
      foreach ($qu as $qu) {
        $userexit = $qu->name;
        $useruid = $qu->uid;
      }

      if ($response->ValidateSubscriberResult == -1) {
        $msg = "Your Subscription has expired. <a href='https://www.etypeservices.com/Subscriber/SignIn.aspx?IssueID=103864&ReturnUrl=https://www.etypeservices.com/Subscriber/ReSubscribe.aspx?PubID=3191'>Click here</a>  to re-subscribe.";
      } else {
        global $user;
        if ($user->uid == 0) {
          if ($userexit != '') {
            if ($response->ValidateSubscriberResult == -5) {
              $msg = "Invalid UserName or Password";

            } else {
              global $user;
              $user = user_load($useruid);
              drupal_session_regenerate();
              drupal_goto($destination);
            }
          } else {
            if ($response->ValidateSubscriberResult == -5) {
              $msg = "Invalid UserName or Password.";
            } else {

              $param1 = array('UserName' => "$username");
              $client = new soapclient('https://etypeservices.com/Get_EmailbyUserName.asmx?WSDL');

              $response1 = $client->GetSubscriberEmail($param1);
              $fields = array(
                'name' => $username,
                'mail' => $response1->GetSubscriberEmailResult,
                'pass' => $Password,
                'status' => 1,
                'init' => $response1->GetSubscriberEmailResult,
                'roles' => array(
                  DRUPAL_AUTHENTICATED_RID => 'authenticated user',
                ),
              );


              $account = user_save('', $fields);
              $param = array('UserName' => "$username");
              $client1 = new soapclient('https://etypeservices.com/Service_GetExpiryDate.asmx?WSDL');
              $response = $client1->SubscriptionExpiryDate($param);
              $query = "select name, uid from users where name='" . $username . "'";
              $qu = db_query($query);
              $useruid = "";
              foreach ($qu as $q) {
                $useruid = $q->uid;
              }

              global $user;
              $user = user_load($useruid);
              drupal_session_regenerate();
              drupal_goto($destination);

            }
          }
        }
      }
    } else {
      $msg = "Invalid UserName or Password.";
    }
  }

  $page['#markup'] = '
<div class="login">
    <form method="POST" action="/login">
        <p class="error">' . $msg . '</p>
        <p><input type="text" name="name" placeholder="User Name" required="required"></p>
        <p><input type="password" name="password" placeholder="Password" required="required"></p>
        <p class="submit"><input type="submit" name="submit" value="Login" /></p>
    </form>
</div>

<div class="login-help">
    <p><a href="/forgot-password">Forgot your password?</a></p>
</div>
  ';
  return $page;
}

