<?php

/**
 * @file
 * Custom functions and hooks for Etype Services
 *
 */

/**
 * Implements hook_menu().
 */
function etype_menu() {

  /* add e-Edition link to user menu */
  $items['login'] = array(
    'title' => 'Login',
    'description' => 'Custom Login Page.',
    'page callback' => '_etype_login',
    'menu_name' => 'user-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * @return string
 */
function _etype_login() {
  $page = array('title' => 'Log In');
  return $page;
}

